server:
  port: 3300
spring:
  application:
    name: my-eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3300/eureka/,http://localhost:3301/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}